In [1]:
import pandas as pd
from surprise import Reader
from surprise import Dataset
from surprise.model_selection import cross_validate
from surprise import NormalPredictor
from surprise import KNNBasic
from surprise import KNNWithMeans
from surprise import KNNWithZScore
from surprise import KNNBaseline
from surprise import SVD
from surprise import BaselineOnly
from surprise import SVDpp
from surprise import NMF
from surprise import SlopeOne
from surprise import CoClustering
from surprise.accuracy import rmse
from surprise import accuracy
from surprise.model_selection import train_test_split
from plotly.offline import init_notebook_mode, plot, iplot
import plotly.graph_objs as go

In [6]:
df = pd.read_csv("C:\\progetti\\low-code-ard-proj\\resyduo_components\\transformation_component\\transformation_storage\\libraries_data\\surprise_df_comp_lib_df_cut_1_1.csv")



In [30]:
surprise_df = df

In [31]:
df.shape


(3367644, 3)

In [33]:
df.shape

(3336936, 3)

In [34]:
#write_report_to_file_2(report_file='report_tag_comp_cleaned.txt',df_name='surprise_tag_comp_cut_5_5_cleaned.csv',row_cut=5,col_cut=5, surprise_df_path='..\\transformation_component\\transformation_storage\\tag_data\\surprise_tag_comp_cut_5_5.csv', original_df_path='..\\transformation_component\\transformation_storage\\tag_data\\df_tag_comp_cut_5_5.csv',surp_df=df)

In [8]:
df.head()

componentID                            libID  rating
0  LEGO Parts  #include <BlynkSimpleMKR1000.h>       0
1  LEGO Parts            #include "LoRa_E32.h"       0
2  LEGO Parts            #include <sys/time.h>       0
3  LEGO Parts             #include <ss_oled.h>       0
4  LEGO Parts      #include "TFT_22_ILI9225.h"       0

In [36]:
#df = df[df.rating != 0] 

In [7]:
df.sort_values(by=['rating'],ascending=False).head(100)

componentID                           libID  \
338693                       Arduino UNO               #include <Wire.h>   
340355                       Arduino UNO              #include <Servo.h>   
340079                       Arduino UNO      #include <LiquidCrystal.h>   
338908                       Arduino UNO                #include <SPI.h>   
6689019                  Arduino Nano R3               #include <Wire.h>   
...                                  ...                             ...   
7301512                 Resistor 10k ohm  #include <LiquidCrystal_I2C.h>   
2254957  Rotary Encoder with Push-Button               #include <Wire.h>   
5275633           Jumper wires (generic)          #include <OneSheeld.h>   
5276574           Jumper wires (generic)           #include <IRremote.h>   
3225278             Breadboard (generic)            #include <WiFi101.h>   

         rating  
338693      290  
340355      253  
340079      209  
338908      207  
6689019     192  
...         ...  
7301512      28  
2254957      28  
5275633      28  
5276574      27  
3225278      27  

[100 rows x 3 columns]

In [38]:
norm_surprise_df = df

In [9]:
df.sort_values(by=['rating'],ascending=False).head(100)

componentID                           libID  \
338693                       Arduino UNO               #include <Wire.h>   
340355                       Arduino UNO              #include <Servo.h>   
340079                       Arduino UNO      #include <LiquidCrystal.h>   
338908                       Arduino UNO                #include <SPI.h>   
6689019                  Arduino Nano R3               #include <Wire.h>   
...                                  ...                             ...   
7301512                 Resistor 10k ohm  #include <LiquidCrystal_I2C.h>   
2254957  Rotary Encoder with Push-Button               #include <Wire.h>   
5275633           Jumper wires (generic)          #include <OneSheeld.h>   
5276574           Jumper wires (generic)           #include <IRremote.h>   
3225278             Breadboard (generic)            #include <WiFi101.h>   

         rating  
338693      290  
340355      253  
340079      209  
338908      207  
6689019     192  
...         ...  
7301512      28  
2254957      28  
5275633      28  
5276574      27  
3225278      27  

[100 rows x 3 columns]

In [40]:
df.head()

tagID                                        componentID  rating
0  solar tracker                          DFRobot LCD Keypad Shield       0
1  solar tracker                      GY21 Temperature and Humidity       0
2  solar tracker  Panel Rotary Potentiometer 6mm shaft diameter ...       0
3  solar tracker                           USB-A to Micro-USB Cable       0
4  solar tracker                                2.54_legs_female_2P       0

In [41]:
df.shape

(3336936, 3)

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3336936 entries, 0 to 3367643
Data columns (total 3 columns):
 #   Column       Dtype 
---  ------       ----- 
 0   tagID        object
 1   componentID  object
 2   rating       int64 
dtypes: int64(1), object(2)
memory usage: 101.8+ MB


In [43]:
print('Dataset shape: {}'.format(df.shape))
print('-Dataset examples-')
print(df.iloc[::200000, :])

Dataset shape: (3336936, 3)
-Dataset examples-
                           tagID  \
0                  solar tracker   
201840                  exercise   
403682                   chiming   
605522          arduino lcd code   
807362                     treno   
1009202                 simulink   
1211044                    blink   
1412884      electronicsprojects   
1614724             pulse sensor   
1816564                education   
2018406                  cranial   
2220246                 handwash   
2422086              geolocation   
2623926  tangible user interface   
2825768                  logging   
3027608                   buzzer   
3229448              meterelogia   

                                               componentID  rating  
0                                DFRobot LCD Keypad Shield       0  
201840                                     Arduino MKR1000       0  
403682              Seeed Studio Grove - OLED Display 1.12       0  
605522              DC-DC (S

## EDA

### Ratings Distribution

In [44]:

init_notebook_mode(connected=True)

data = df['rating'].value_counts().sort_index(ascending=False)
trace = go.Bar(x = data.index,
               text = ['{:.1f} %'.format(val) for val in (data.values / df.shape[0] * 100)],
               textposition = 'auto',
               textfont = dict(color = '#000000'),
               y = data.values,
               )
# Create layout
layout = dict(title = 'Distribution Of {} book-ratings'.format(df.shape[0]),
              xaxis = dict(title = 'Rating'),
              yaxis = dict(title = 'Count'), width=800, height=400)
# Create plot
fig = go.Figure(data=[trace], layout=layout)
iplot(fig)

We can see that over 62% of all ratings in the data are 0, and very few ratings are 1 or 2, or 3, low rating books mean they are generally really bad.

### Ratings Distribution By Book

In [45]:
df.columns

Index(['tagID', 'componentID', 'rating'], dtype='object')

In [10]:
df_without_zero = df[df.rating != 0] 
df_without_zero.head(20)

componentID                         libID  rating
215                       LEGO Parts       #include <ArduinoBLE.h>       1
529                       LEGO Parts  #include <Arduino_LSM9DS1.h>       1
2683   Female to Female jumper wires      #include <MotorShield.h>       1
3568   Female to Female jumper wires            #include <Servo.h>       1
3707    sparkfun micro oled breakout             #include <Wire.h>       1
3922    sparkfun micro oled breakout              #include <SPI.h>       1
5025    sparkfun micro oled breakout    #include <SFE_MicroOLED.h>       1
5508                         max4236             #include <Wire.h>       1
5723                         max4236              #include <SPI.h>       1
6891                         max4236          #include <WiFi101.h>       1
8767                           Paper            #include "Timer.h"       1
8971                           Paper            #include <Servo.h>       1
9292                  JST connectors            #include <Timer.h>       2
9325                  JST connectors              #include <SPI.h>       2
9485                  JST connectors          #include <Network.h>       2
9504                  JST connectors              #include <Dns.h>       1
9543                  JST connectors      #include <ArduinoJson.h>       1
10002                 JST connectors          #include <avr/wdt.h>       2
10409                 JST connectors     #include <PubSubClient.h>       2
10617                 JST connectors         #include <Ethernet.h>       2

In [14]:
# Number of ratings per book
data = df_without_zero.groupby('libID')['rating'].count().clip(upper=50)

# Create trace
trace = go.Histogram(x = data.values,
                     name = 'Ratings',
                     xbins = dict(start = 0,
                                  end = 50,
                                  size =1))
# Create layout
layout = go.Layout(title = 'Distribution Of Number of Components per Library Cut-Off (1,1)',
                   xaxis = dict(title = 'Number of Components per Library used in a single project'),
                   yaxis = dict(title = 'Count'),
                   bargap = 0.2,  height=1000,
                       font=dict(
                        family="sans serif",
                        size=32
                        ))

# Create plot
fig = go.Figure(data=[trace], layout=layout)
iplot(fig)

In [15]:
df55 = pd.read_csv("C:\\progetti\\low-code-ard-proj\\resyduo_components\\transformation_component\\transformation_storage\\libraries_data\\surprise_df_comp_lib_df_cut_5_5.csv")


df_without_zero55 = df55[df55.rating != 0] 
 
df_without_zero.head(20)

# Number of ratings per book
data = df_without_zero.groupby('componentID')['rating'].count().clip(upper=50)

# Create trace
trace = go.Histogram(x = data.values,
                     name = 'Ratings',
                     xbins = dict(start = 0,
                                  end = 50,
                                  size =1))
# Create layout
layout = go.Layout(title = 'Distribution Of Number of Components per Library Cut-Off (5,5)',
                   xaxis = dict(title = 'Number of Components per Library used in a single project'),
                   yaxis = dict(title = 'Count'),
                   bargap = 0.2,  height=1000,
                       font=dict(
                        family="sans serif",
                        size=32
                        ))

# Create plot
fig = go.Figure(data=[trace], layout=layout)
iplot(fig)

In [52]:
from recommender import Recommender
import os
recommender = Recommender()
def write_report_to_file_2 (report_file, df_name, row_cut, col_cut,surprise_df_path,original_df_path, surp_df):
    df = pd.read_csv(original_df_path)
    report = recommender.predict_and_validate_2(surprise_df=surp_df,sim_options={
                'name': 'msd',
                'user_based': True,
                'min_support':1,
                'shrinkage':0
                },threshold = 0.2)
    #print("REPORT",report)
    file_stats = os.stat(surprise_df_path)
    file_size = round(file_stats.st_size / (1024 * 1024),4)

    s = ''
    precision_avg = 0.0
    recall_avg = 0.0
    accuracy_avg = 0.0
    fpr_avg = 0.0
    sr_avg = 0.0
    mae_avg = 0.0
    rmse_avg = 0.0
    for i in range(0, len(report)):
        s +='fold'+str(i+1)+" "+ "&"+ str(round(report[i]['precision'],4))+" "+"&"+ str(round(report[i]['recall'],4))+" ""&"+ str(round(report[i]['accuracy'],4))+" ""&"+ str(round(report[i]['false_positive_rate'],4))+" ""&"+ str(round(report[i]['success_rate'],4))+" "+"&"+str(round(report[i]['mae'],4))+"&"+str(round(report[i]['rmse'],4))+"\\\\"
        precision_avg += report[i]['precision']
        recall_avg += report[i]['recall']
        accuracy_avg += report[i]['accuracy']
        fpr_avg += report[i]['false_positive_rate']
        sr_avg += report[i]['success_rate']
        mae_avg += report[i]['mae']
        rmse_avg += report[i]['rmse']
        #AVG
    precision_avg = round(precision_avg/len(report),2)
    recall_avg = round(recall_avg /len(report),2)
    accuracy_avg = round(accuracy_avg /len(report),2)
    fpr_avg = round(fpr_avg /len(report),2)
    sr_avg = round(sr_avg /len(report),2)
    mae_avg  = round(mae_avg /len(report),2)
    rmse_avg = round(rmse_avg /len(report),2)
    s += "\\cline{1-8}"
    s +='average'+" "+ "&"+ str(precision_avg)+" "+"&"+ str(recall_avg)+" ""&"+str(accuracy_avg)+" ""&"+ str(fpr_avg)+" ""&"+str(sr_avg)+" "+"&"+str(mae_avg)+"&"+str(rmse_avg)+"\\\\"
    string_report = """
############# DataFrame :  """+df_name+"""#################


\\begin{table}[H]
\centering
\\begin{tabular}{|l|c|c|c|c|c|c|c|}
\hline
\multicolumn{8}{|c|}{"""+str(df_name.replace("_","\_"))+"""} \\\\
\cline{1-8}
\multicolumn{3}{|c|}{Cut-off (row-col)} & \multicolumn{3}{c|}{File Size} & \multicolumn{2}{c|}{Dimension (row,col)}\\\\
\cline{1-8}
\multicolumn{3}{|c|}{"""+str(row_cut)+""","""+str(col_cut)+"""} & \multicolumn{3}{c|}{"""+str(file_size)+"""} & \multicolumn{1}{c|}{"""+str(len(df.index))+"""} & \multicolumn{1}{c|}{"""+str(len(df.columns))+"""}\\\\
\cline{1-8}
\multicolumn{1}{|c|}{fold} & precision & recall & accuracy & false positive rate & success rate &MAE &RMSE\\\\

\hline
"""+s+"""
\hline
\end{tabular}
\caption{Analisi dei risultati di predizione per il dataframe :"""+str(df_name.replace("_","\_"))+"""}
\end{table}


"""


    with open(report_file, 'a') as file:
        file.write(string_report)

In [53]:
write_report_to_file_2(report_file='report_tag_comp_cleaned_data.txt',df_name='surprise_tag_comp_cut_5_5_cleaned_cv10.csv',row_cut=5,col_cut=5, surprise_df_path='..\\transformation_component\\transformation_storage\\tag_data\\surprise_tag_comp_cut_5_5.csv', original_df_path='..\\transformation_component\\transformation_storage\\tag_data\\df_tag_comp_cut_5_5.csv',surp_df= df)

Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.


In [ ]:
df_without_zero.groupby('componentID')['rating'].count().reset_index().sort_values('rating', ascending=False)[:30]

componentID  rating
404                                  Arduino UNO    1246
896                       Jumper wires (generic)     882
389                              Arduino Nano R3     832
484                         Breadboard (generic)     735
1340                            Resistor 10k ohm     550
934                                LED (generic)     531
375                            Arduino Mega 2560     487
495                                       Buzzer     435
1810       Ultrasonic Sensor - HC-SR04 (Generic)     403
1343                             Resistor 1k ohm     388
1349                            Resistor 220 ohm     356
1609             SparkFun Pushbutton switch 12mm     330
143                                5 mm LED: Red     323
1422              Rotary potentiometer (generic)     319
787                       HC-05 Bluetooth Module     314
193                         9V battery (generic)     311
1355                            Resistor 330 ohm     288
1350                            Resistor 221 ohm     283
1429                      SG90 Micro-servo motor     262
295   Adafruit Standard LCD - 16x2 White on Blue     257
1548    SparkFun Arduino Pro Mini 328 - 5V/16MHz     230
1337                            Resistor 100 ohm     226
1053                    Male/Female Jumper Wires     220
373                              Arduino MKR1000     213
1514                                Slide Switch     205
1506                   Servos (Tower Pro MG996R)     189
767               General Purpose Transistor NPN     188
1801                            USB-A to B Cable     186
1324                             Relay (generic)     186
142                              5 mm LED: Green     184

Most of the books received less than 5 ratings, and very few books have many ratings, although the most rated book has received 2,502 ratings.


df = df[df.componentID != "Arduino UNO"]
df = df[df.componentID != "Jumper wires (generic)"]
df = df[df.componentID !="Arduino Nano R3"]
df = df[df.componentID != "Breadboard (generic)"]
df = df[df.componentID != "Resistor 10k ohm"]
df = df[df.componentID != "LED (generic)"]
df = df[df.componentID != "Arduino Mega 2560"]
df = df[df.componentID != "Buzzer	435"]
df = df[df.componentID != " "]
df = df[df.componentID != "Resistor 220 ohm"]
df = df[df.componentID != "Resistor 1k ohm"]
df = df[df.componentID != "Resistor 330 ohm"]
df = df[df.componentID != "5 mm LED: Red"]
df = df[df.componentID != "Rotary potentiometer (generic)"]
df = df[df.componentID != "9V battery (generic)"]
df = df[df.componentID != "Resistor 100 ohm"]
df = df[df.componentID != "Relay (generic)"]
df = df[df.componentID != "5 mm LED: Green"]
df = df[df.componentID != "General Purpose Transistor NPN"]


df_without_zero = df[df.rating != 0] 
df_without_zero.groupby('componentID')['rating'].count().reset_index().sort_values('rating', ascending=False)[:20]

df = df[df.componentID != "Buzzer"]
df = df[df.componentID != "SparkFun Pushbutton switch 12mm"]
df = df[df.componentID != "Slide Switch"]
df = df[df.componentID != "USB-A to B Cable"]
df = df[df.componentID != "Resistor 221 ohm"]
df = df[df.componentID != "Male/Female Jumper Wires"]
df = df[df.componentID != "Solderless Breadboard Full Size"]

df_without_zero = df[df.rating != 0] 
df_without_zero.groupby('componentID')['rating'].count().reset_index().sort_values('rating', ascending=False)[:20]

In [ ]:
df.groupby('componentID')['rating'].count().reset_index().sort_values('rating', ascending=False)[:10]

componentID  rating
404                             Arduino UNO    1246
896                  Jumper wires (generic)     882
389                         Arduino Nano R3     832
484                    Breadboard (generic)     735
1340                       Resistor 10k ohm     550
934                           LED (generic)     531
375                       Arduino Mega 2560     487
495                                  Buzzer     435
1810  Ultrasonic Sensor - HC-SR04 (Generic)     403
1343                        Resistor 1k ohm     388

In [ ]:
from sklearn import preprocessing
import pandas as pd
def scale_normalizer(df,min, max, column):
    scaled_df=df
    display("max",df["rating"].max())
    scaler = preprocessing.MinMaxScaler(feature_range=(min, max))
    scaled_df["rating"] = scaler.fit_transform(df[[column]])
    #scaled_df = pd.DataFrame(d, "rating")
    #display(scaled_df.head())
    #display(df.head())
    display("norm MAx ",df["rating"].max())
    return scaled_df

df = scale_normalizer(df, 0,10, "rating")

'max'

516

C:\Users\Skynetth\AppData\Local\Temp\ipykernel_1044\3093314600.py:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



'norm MAx '

9.999999999999998

### Ratings Distribution By User

In [ ]:
# Number of ratings per user
data = df.groupby('componentID')['rating'].count().clip(upper=50)

# Create trace
trace = go.Histogram(x = data.values,
                     name = 'Ratings',
                     xbins = dict(start = 0,
                                  end = 50,
                                  size = 2))
# Create layout
layout = go.Layout(title = 'Distribution Of Number of Ratings Per User (Clipped at 50)',
                   xaxis = dict(title = 'Componente Per Tag'),
                   yaxis = dict(title = 'Count'),
                   bargap = 0.2)

# Create plot
fig = go.Figure(data=[trace], layout=layout)
iplot(fig)

In [ ]:
df.groupby('tagID')['rating'].count().reset_index().sort_values('rating', ascending=False)[:10]

tagID  rating
690      home automation     753
766   internet of things     680
1252            robotics     625
83               arduino     536
828                  led     522
1224      remote control     516
857               lights     447
967           monitoring     424
438              display     410
1355    smart appliances     403

Most of the users gave less than 5 ratings, and very few users gave many ratings, although the most productive user have given 13,602 ratings.

I'm sure you have noticed that the above two charts share the same distribution. The number of ratings per movie and the number of ratings per user decay exponentially.

To reduce the dimensionality of the dataset, we will filter out rarely rated movies and rarely rating users.

In [ ]:
df.groupby('componentID')['rating'].count().reset_index().sort_values('rating', ascending=True)[:10]

componentID  rating
356                       Arduino MKR Connector Carrier       2
669                                      Df player mini       2
223                                   Adafruit 1.44 TFT       2
370                                Arduino MKR WAN 1310       2
1273                          QMC5883l Compass (GY-271)       2
1716                                 Temperature sensor       2
1185  Panasonic 2 rechargeable Panasonic NCR18650B L...       2
1020  MLX90615 Digital Infrared Temperature Sensor M...       3
23                                            10 ohm 2W       3
22                                         10 White LED       3

In [ ]:
min_book_ratings = 1
filter_books = df['componentID'].value_counts() > min_book_ratings
filter_books = filter_books[filter_books].index.tolist()

min_user_ratings = 1
filter_users = df['tagID'].value_counts() > min_user_ratings
filter_users = filter_users[filter_users].index.tolist()

df_new = df[(df['componentID'].isin(filter_books)) & (df['tagID'].isin(filter_users))]
print('The original data frame shape:\t{}'.format(df.shape))
print('The new data frame shape:\t{}'.format(df_new.shape))

The original data frame shape:	(43917, 3)
The new data frame shape:	(43917, 3)


# CroSS Validation 

Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.
Computing the msd similarity matrix...
Done computing similarity matrix.


In [ ]:
asdasdasd

NameError: name 'asdasdasd' is not defined

## Surprise

To load a dataset from a pandas dataframe, we will use the load_from_df() method, we will also need a Reader object, and the rating_scale parameter must be specified. The dataframe must have three columns, corresponding to the user ids, the item ids, and the ratings in this order. Each row thus corresponds to a given rating.

In [ ]:
reader = Reader(rating_scale=(0, 10))
data = Dataset.load_from_df(df_new[['tagID', 'componentID', 'rating']], reader)

With the Surprise library, we will benchmark the following algorithms

### Basic algorithms

#### NormalPredictor

* NormalPredictor algorithm predicts a random rating based on the distribution of the training set, which is assumed to be normal. This is one of the most basic algorithms that do not do much work.

#### BaselineOnly

* BasiclineOnly algorithm predicts the baseline estimate for given user and item.

### k-NN algorithms

#### KNNBasic

* KNNBasic is a basic collaborative filtering algorithm.

#### KNNWithMeans

* KNNWithMeans is basic collaborative filtering algorithm, taking into account the mean ratings of each user.

#### KNNWithZScore

* KNNWithZScore is a basic collaborative filtering algorithm, taking into account the z-score normalization of each user.

#### KNNBaseline

* KNNBaseline is a basic collaborative filtering algorithm taking into account a baseline rating.

### Matrix Factorization-based algorithms

#### SVD

* SVD algorithm is equivalent to Probabilistic Matrix Factorization (http://papers.nips.cc/paper/3208-probabilistic-matrix-factorization.pdf)

#### SVDpp

* The SVDpp algorithm is an extension of SVD that takes into account implicit ratings.

#### NMF

* NMF is a collaborative filtering algorithm based on Non-negative Matrix Factorization. It is very similar with SVD.

### Slope One

* Slope One is a straightforward implementation of the SlopeOne algorithm. (https://arxiv.org/abs/cs/0702144)

### Co-clustering

* Co-clustering is a collaborative filtering algorithm based on co-clustering (http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.113.6458&rep=rep1&type=pdf)


We use rmse as our accuracy metric for the predictions.

In [ ]:
"""benchmark = []
# Iterate over all algorithms
for algorithm in [SVD(), SVDpp(), SlopeOne(), NMF(), NormalPredictor(), KNNBaseline(), KNNBasic(), KNNWithMeans(), KNNWithZScore(), BaselineOnly(), CoClustering()]:
    # Perform cross validation
    results = cross_validate(algorithm, data, measures=['RMSE'], cv=3, verbose=False)
    
    # Get results & append algorithm name
    tmp = pd.DataFrame.from_dict(results).mean(axis=0)
    tmp = tmp.append(pd.Series([str(algorithm).split(' ')[0].split('.')[-1]], index=['Algorithm']))
    benchmark.append(tmp)"""

"benchmark = []\n# Iterate over all algorithms\nfor algorithm in [SVD(), SVDpp(), SlopeOne(), NMF(), NormalPredictor(), KNNBaseline(), KNNBasic(), KNNWithMeans(), KNNWithZScore(), BaselineOnly(), CoClustering()]:\n    # Perform cross validation\n    results = cross_validate(algorithm, data, measures=['RMSE'], cv=3, verbose=False)\n    \n    # Get results & append algorithm name\n    tmp = pd.DataFrame.from_dict(results).mean(axis=0)\n    tmp = tmp.append(pd.Series([str(algorithm).split(' ')[0].split('.')[-1]], index=['Algorithm']))\n    benchmark.append(tmp)"

In [ ]:
#surprise_results = pd.DataFrame(benchmark).set_index('Algorithm').sort_values('test_rmse')

In [ ]:
#surprise_results

BaselineOnly algorithm gave us the best rmse, therefore, we will proceed further with BaselineOnly and use Alternating Least Squares (ALS).

In [ ]:
print('Using ALS')
bsl_options = {'method': 'als',
               'n_epochs': 5,
               'reg_u': 12,
               'reg_i': 5
               }
#algo = BaselineOnly(bsl_options=bsl_options)
algo = NMF()
cross_validate(algo, data, measures=['RMSE'], cv=3, verbose=False)

Using ALS


{'test_rmse': array([0.12831419, 0.12201593, 0.13319904]),
 'fit_time': (0.6629974842071533, 0.6839854717254639, 0.6270005702972412),
 'test_time': (0.07401394844055176, 0.07400012016296387, 0.07485508918762207)}

We use the train_test_split() to sample a trainset and a testset with given sizes, and use the accuracy metric of rmse. We’ll then use the fit() method which will train the algorithm on the trainset, and the test() method which will return the predictions made from the testset

In [ ]:
trainset, testset = train_test_split(data, test_size=0.25)
algo = BaselineOnly(bsl_options=bsl_options)
predictions = algo.fit(trainset).test(testset)
accuracy.rmse(predictions)

Estimating biases using als...
RMSE: 0.1433


0.14327397416801882

In [ ]:
predictions

[Prediction(uid='home automation', iid='Arduino Micro', r_ui=1.2970873786407768, est=1.085194037469422, details={'was_impossible': False}),
 Prediction(uid='tools', iid='NeoPixel strip', r_ui=1.0, est=1.0062485472641278, details={'was_impossible': False}),
 Prediction(uid='lilypad', iid='Buzzer', r_ui=1.0, est=1.0316948330404245, details={'was_impossible': False}),
 Prediction(uid='guitar', iid='Resistor 6.8k', r_ui=1.0, est=0.9951775164898214, details={'was_impossible': False}),
 Prediction(uid='wi-fi', iid='RobotGeek Sensor Shield', r_ui=1.0, est=0.9866991511469435, details={'was_impossible': False}),
 Prediction(uid='time', iid='Resistor 2.21k ohm', r_ui=1.0, est=0.9992339982753599, details={'was_impossible': False}),
 Prediction(uid='samsung', iid='Jumper wires (generic)', r_ui=1.0, est=1.066829948464257, details={'was_impossible': False}),
 Prediction(uid='arduino project', iid='SparkFun Dual H-Bridge motor drivers L298', r_ui=1.0, est=1.0210954273480182, details={'was_impossible'

In [ ]:
# dump.dump('./dump_file', predictions, algo)
# predictions, algo = dump.load('./dump_file')

In [ ]:
trainset = algo.trainset
print(algo.__class__.__name__)

BaselineOnly


To inspect our predictions in details, we are going to build a pandas data frame with all the predictions.

In [ ]:
uid = str("home automation")  # raw user id (as in the ratings file). They are **strings**!
iid = str("Arduino UNO")  # raw item id (as in the ratings file). They are **strings**!

# get a prediction for specific users and items.
pred = algo.predict(uid, iid, verbose=True)

user: home automation item: Arduino UNO r_ui = None   est = 1.19   {'was_impossible': False}


In [ ]:
def get_Iu(uid):
    """ return the number of items rated by given user
    args: 
      uid: the id of the user
    returns: 
      the number of items rated by the user
    """
    try:
        return len(trainset.ur[trainset.to_inner_uid(uid)])
    except ValueError: # user was not part of the trainset
        return 0
    
def get_Ui(iid):
    """ return number of users that have rated given item
    args:
      iid: the raw id of the item
    returns:
      the number of users that have rated the item.
    """
    try: 
        return len(trainset.ir[trainset.to_inner_iid(iid)])
    except ValueError:
        return 0
    
df = pd.DataFrame(predictions, columns=['uid', 'iid', 'rui', 'est', 'details'])
df['Iu'] = df.uid.apply(get_Iu)
df['Ui'] = df.iid.apply(get_Ui)
df['err'] = abs(df.est - df.rui)

In [ ]:
df.head(100)

uid  \
0                             home automation   
1                                       tools   
2                                     lilypad   
3                                      guitar   
4                                       wi-fi   
..                                        ...   
95  speed measurement using ir sensor arduino   
96                                 monitoring   
97                              photoresistor   
98                                        ham   
99                                    mkr1000   

                                                 iid       rui       est  \
0                                      Arduino Micro  1.297087  1.085194   
1                                     NeoPixel strip  1.000000  1.006249   
2                                             Buzzer  1.000000  1.031695   
3                                      Resistor 6.8k  1.000000  0.995178   
4                            RobotGeek Sensor Shield  1.000000  0.986699   
..                                               ...       ...       ...   
95                                            Buzzer  1.000000  1.020174   
96                                   Adafruit TMP006  1.000000  1.035453   
97                                            Buzzer  1.000000  1.019994   
98                             Speaker: 0.25W 8 ohms  1.000000  1.008180   
99  Pocket Solder- 60/40 Rosin Core 0.031'' diameter  1.000000  0.983763   

                      details   Iu   Ui       err  
0   {'was_impossible': False}  557  111  0.211893  
1   {'was_impossible': False}   14   53  0.006249  
2   {'was_impossible': False}    4  323  0.031695  
3   {'was_impossible': False}   18    4  0.004822  
4   {'was_impossible': False}   12   43  0.013301  
..                        ...  ...  ...       ...  
95  {'was_impossible': False}    6  323  0.020174  
96  {'was_impossible': False}  319    4  0.035453  
97  {'was_impossible': False}    6  323  0.019994  
98  {'was_impossible': False}   11   85  0.008180  
99  {'was_impossible': False}   10   11  0.016237  

[100 rows x 8 columns]

In [ ]:

def get_precalculated_predictions(surprise_df, column_1, column_2):
    predictions = []
    trainset, testset = train_test_split(data, test_size=0.25)
    bsl_options = {'method': 'als',
                    'n_epochs': 5,
                    'reg_u': 12,
                    'reg_i': 5
                    }
    algo = BaselineOnly(bsl_options=bsl_options)
    algo.fit(trainset).test(testset)
    display(surprise_df)
    for uid in set(surprise_df[column_1]):
        for iid in set(surprise_df[column_2]):
            p = algo.predict(uid, iid)
            predictions.append(p)
    return predictions
            
full_predictions = get_precalculated_predictions(norm_surprise_df, "tagID", "componentID")

Estimating biases using als...


tagID                   componentID    rating
110      solar tracker              Resistor 330 ohm  1.017476
162      solar tracker              Resistor 220 ohm  1.000000
248      solar tracker            Resistor 2.21k ohm  1.000000
337      solar tracker        HC-05 Bluetooth Module  1.000000
587      solar tracker  Through Hole Resistor 10 ohm  1.000000
...                ...                           ...       ...
3365832        circuit              Resistor 220 ohm  1.000000
3366017        circuit                        Buzzer  1.000000
3366311        circuit                 5 mm LED: Red  1.000000
3367233        circuit          Breadboard (generic)  1.000000
3367455        circuit                   Arduino UNO  1.000000

[43917 rows x 3 columns]

In [ ]:
len(full_predictions[0])

5

In [ ]:

#display(len(top_10_recommendations))

In [ ]:
import json
def write_recommendation_to_file(top_n_recommendations,file):
    with open(file, 'w') as convert_file:
        convert_file.write(json.dumps(top_n_recommendations))

def read_recommendation_from_file(file='recommendation_top10_project_component_0_to_276_cut_5_10.json'):
    # reading the data from the file
    with open(file) as f:
        data = f.read()
    js = json.loads(data)
    return js

In [ ]:
best_predictions = df.sort_values(by='err')[:10]
worst_predictions = df.sort_values(by='err')[-10:]

In [ ]:
df.index

RangeIndex(start=0, stop=10980, step=1)

In [ ]:
best_predictions

uid                                                iid  rui  \
8983       party                 SparkFun USB Cable A to B - 6 Foot  1.0   
8987        lack                       TL072 based audio amplifier   1.0   
5475      safety                       SparkFun Level Shifter Board  1.0   
7405     ws2812b                                             WS2812  1.0   
2921         ecg                              JLCPCB Customized PCB  1.0   
10893     garden                  Digilent Voltage Regulator Module  1.0   
3736        game  Texas Instruments Shift Register- Serial to Pa...  1.0   
9795      sigars                            Linear Regulator (7805)  1.0   
7377   behaviour                                        LIDAR Laser  1.0   
9974    learning                                    Relay (generic)  1.0   

            est                    details   Iu   Ui           err  
8983   1.000001  {'was_impossible': False}    5    7  7.201094e-07  
8987   0.999996  {'was_impossible': False}   12   24  3.669047e-06  
5475   1.000006  {'was_impossible': False}   71   23  6.212355e-06  
7405   0.999990  {'was_impossible': False}   34    5  1.010970e-05  
2921   1.000014  {'was_impossible': False}   15   62  1.425046e-05  
10893  1.000015  {'was_impossible': False}  106   12  1.454476e-05  
3736   1.000015  {'was_impossible': False}   77   52  1.471680e-05  
9795   1.000017  {'was_impossible': False}    6  115  1.663550e-05  
7377   0.999983  {'was_impossible': False}    5   11  1.680834e-05  
9974   1.000017  {'was_impossible': False}   12  129  1.713060e-05

The above are the best predictions, and they are not lucky guesses. Because Ui is anywhere between 26 to 146, they are not really small, meaning that significant number of users have rated the target book.

In [ ]:
worst_predictions

uid                     iid        rui       est  \
10136          communication             Arduino UNO   3.062136  1.155568   
6568                robotics  Jumper wires (generic)   3.324272  1.145560   
628    environmental sensing             Arduino UNO   3.603883  1.161169   
160                 embedded             Arduino UNO   3.743689  1.154461   
7021              monitoring             Arduino UNO   3.761165  1.163363   
4956                     led         Arduino Nano R3   3.883495  1.108720   
8401         home automation         Arduino Nano R3   4.792233  1.126689   
1926         home automation  Jumper wires (generic)   5.368932  1.141937   
10274                arduino             Arduino UNO   5.718447  1.144297   
352          home automation             Arduino UNO  10.000000  1.188118   

                         details   Iu   Ui       err  
10136  {'was_impossible': False}  179  927  1.906568  
6568   {'was_impossible': False}  452  648  2.178712  
628    {'was_impossible': False}  304  927  2.442714  
160    {'was_impossible': False}  238  927  2.589229  
7021   {'was_impossible': False}  319  927  2.597802  
4956   {'was_impossible': False}  387  630  2.774775  
8401   {'was_impossible': False}  557  630  3.665544  
1926   {'was_impossible': False}  557  648  4.226995  
10274  {'was_impossible': False}  387  927  4.574150  
352    {'was_impossible': False}  557  927  8.811882

The worst predictions look pretty surprise. Let's look in more details of the last one ISBN "055358264X", the book was rated by 47 users, user "26544" rated 10, our BaselineOnly algorithm predicts 0.

In [ ]:
uid = str("remote control")  # raw user id (as in the ratings file). They are **strings**!
iid = str("Arduino UNO")  # raw item id (as in the ratings file). They are **strings**!

# get a prediction for specific users and items.
pred = algo.predict(uid, iid,r_ui =5.718447, verbose=True)

user: remote control item: Arduino UNO r_ui = 5.72   est = 1.18   {'was_impossible': False}


In [ ]:
df_new.loc[df_new['componentID'] == 'Arduino UNO']['rating'].describe()

count    1246.000000
mean        1.123803
std         0.512877
min         1.000000
25%         1.000000
50%         1.017476
75%         1.052427
max        10.000000
Name: rating, dtype: float64

In [ ]:
df.loc[df['uid'] == 'display']

uid                                                iid       rui  \
59     display                      7 Segment LED Display InfoVue  1.034951   
269    display                       Graphic OLED 128 x 32 Pixels  1.000000   
493    display                          Analog joystick (Generic)  1.034951   
502    display  SparkFun Triple Axis Accelerometer and Gyro Br...  1.017476   
568    display                               Breadboard (generic)  1.996117   
...        ...                                                ...       ...   
10422  display                    Solderless Breadboard Full Size  1.139806   
10533  display                                   12V Power Supply  1.000000   
10566  display                                   Resistor 20k ohm  1.000000   
10693  display                        RGB Diffused Common Cathode  1.000000   
10787  display                                       AA Batteries  1.000000   

            est                    details   Iu   Ui       err  
59     1.038542  {'was_impossible': False}  326   13  0.003591  
269    1.032878  {'was_impossible': False}  326    6  0.032878  
493    1.041075  {'was_impossible': False}  326   50  0.006123  
502    1.041033  {'was_impossible': False}  326   40  0.023557  
568    1.100046  {'was_impossible': False}  326  550  0.896070  
...         ...                        ...  ...  ...       ...  
10422  1.051269  {'was_impossible': False}  326  132  0.088537  
10533  1.039396  {'was_impossible': False}  326    7  0.039396  
10566  1.034447  {'was_impossible': False}  326    5  0.034447  
10693  1.051190  {'was_impossible': False}  326  111  0.051190  
10787  1.046325  {'was_impossible': False}  326   81  0.046325  

[84 rows x 8 columns]

In [ ]:
df_new.groupby('tagID')['rating'].count().reset_index().sort_values('rating', ascending=True)[:100]

tagID  rating
0                                  ''home automation''       6
713                   how to program an lcd on arduino       6
712                      how to make voice control car       6
711  how to make countdown timer relay using arduin...       6
710  how to make a stepper motor speed controller u...       6
..                                                 ...     ...
491                              electronicengineering       6
489                                  electronic locker       6
486                                    electromagnetic       6
484                             electrical engineering       6
483                                     electric shock       6

[100 rows x 2 columns]

In [ ]:
df.loc[df['uid'] == 'pianomidi']

Empty DataFrame
Columns: [uid, iid, rui, est, details, Iu, Ui, err]
Index: []

In [ ]:
import matplotlib.pyplot as plt
%matplotlib notebook

df_new.loc[df_new['componentID'] == 'Rubber feet']['rating'].hist()
plt.xlabel('rating')
plt.ylabel('Number of ratings')
plt.title('Number of ratings item Rubber feet has received')
plt.show();

<IPython.core.display.Javascript object>

It turns out, most of the ratings this book received was "0", in another word, most of the users in the data rated this book "0", only very few users rated "10". Same with the other predictions in "worst predictions" list. It seems that for each prediction, the users are some kind of outsiders.

In [ ]:
from collections import defaultdict

def get_top_n( predictions, n=10):
    """Return the top-N recommendation for each user from a set of predictions.

    Args:
        predictions(list of Prediction objects): The list of predictions, as
            returned by the test method of an algorithm.
        n(int): The number of recommendation to output for each user. Default
            is 10.

    Returns:
    A dict where keys are user (raw) ids and values are lists of tuples:
        [(raw item id, rating estimation), ...] of size n.
    """

    # First map the predictions to each user.
    
    top_n = defaultdict(list)
    for  uid,iid, true_r, est, _ in predictions:
        if( true_r == None ):
            true_r = 0
        top_n[uid].append((iid, est,float(true_r)))

    # Then sort the predictions for each user and retrieve the k highest ones.
    for iid, user_ratings in top_n.items():
        user_ratings.sort(key=lambda x: x[2], reverse=True)
        top_n[iid] = user_ratings[:n]

    return top_n

top_n = get_top_n( full_predictions, n=10)

In [ ]:
uid = str("sleep")  # raw user id (as in the ratings file). They are **strings**!
iid = str("Push Button")  # raw item id (as in the ratings file). They are **strings**!

# get a prediction for specific users and items.
pred = algo.predict(uid, iid,verbose=True)

user: sleep      item: Push Button r_ui = None   est = 0.99   {'was_impossible': False}


In [ ]:
top_n

In [ ]:

write_recommendation_to_file(top_n_recommendations = dict(top_n), file = 'C:\\progetti\\low-code-ard-proj\\resyduo_components\\recommender_component\\recommendation_storage\\top10_rec_surprise_tag_comp_cut_5_5_new_approach.json')

defaultdict(list,
            {'sleep': [('DC Power Connector Jack', 0.9840028147899536, 0.0),
              ('Zerynth Shield', 0.9932884903483435, 0.0),
              ('1300 mAh LiPo Battery 7.4V 30C', 0.9862355488999148, 0.0),
              ('Push Button', 0.9850999386735853, 0.0),
              ('DFRobot Raspberry Pi Camera Module', 0.9842126792628493, 0.0),
              ('Digilent 5V 2.5A Switching Power Supply',
               0.9882200701063524,
               0.0),
              ('Extra piece of wood (same size of the layout)',
               0.980044589773477,
               0.0),
              ('xbox 360 controller', 0.9942531561304108, 0.0),
              ('AX-12A', 0.9956019099681849, 0.0),
              ('Led Lamp', 0.9847850150539231, 0.0)],
             'translator': [('DC Power Connector Jack',
               0.9895699109129898,
               0.0),
              ('Zerynth Shield', 0.9988555864713798, 0.0),
              ('1300 mAh LiPo Battery 7.4V 30C', 0.991802645022